import AppKit

/// Saves and restores the general pasteboard around automated copy/paste so the
/// user's clipboard is left exactly as it was.
@MainActor
struct ClipboardSnapshot {
    private let items: [[NSPasteboard.PasteboardType: Data]]

    init(_ pasteboard: NSPasteboard = .general) {
        items = (pasteboard.pasteboardItems ?? []).map { item in
            var representations: [NSPasteboard.PasteboardType: Data] = [:]
            for type in item.types {
                representations[type] = item.data(forType: type)
            }
            return representations
        }
    }

    /// Restores the saved contents unless something else wrote to the pasteboard after us
    /// (`expectedChangeCount`), in which case the newer contents win.
    func restore(_ pasteboard: NSPasteboard = .general, ifChangeCountIs expectedChangeCount: Int? = nil) {
        if let expectedChangeCount, pasteboard.changeCount != expectedChangeCount { return }
        pasteboard.clearContents()
        guard !items.isEmpty else { return }
        pasteboard.writeObjects(items.map { representations in
            let item = NSPasteboardItem()
            for (type, data) in representations {
                item.setData(data, forType: type)
            }
            return item
        })
    }
}

@MainActor
enum Clipboard {
    /// nspasteboard.org markers: clipboard managers should not record our temporary text.
    private static let transientTypes = [
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
    ]

    /// Writes text that only exists to be pasted once. Returns the resulting change count.
    @discardableResult
    static func writeTransient(_ text: String, to pasteboard: NSPasteboard = .general) -> Int {
        pasteboard.clearContents()
        let item = NSPasteboardItem()
        item.setString(text, forType: .string)
        for type in transientTypes {
            item.setData(Data(), forType: type)
        }
        pasteboard.writeObjects([item])
        return pasteboard.changeCount
    }

    static func write(_ text: String, to pasteboard: NSPasteboard = .general) {
        pasteboard.clearContents()
        pasteboard.setString(text, forType: .string)
    }

    /// Waits until another process writes to the pasteboard (e.g. after we sent ⌘C).
    static func waitForChange(from changeCount: Int, timeout: Duration = .milliseconds(800), pasteboard: NSPasteboard = .general) async -> Bool {
        let deadline = ContinuousClock.now + timeout
        while ContinuousClock.now < deadline {
            if pasteboard.changeCount != changeCount { return true }
            try? await Task.sleep(for: .milliseconds(15))
        }
        return pasteboard.changeCount != changeCount
    }
}
